stages:
  - deploy

deploy:
  stage: deploy
  image: ${BUILDER_PATH} 
  tags:
    - docker
  script:
    - pip install uv
    - echo "$CI_COMMIT_TAG" > VERSION
    - uv build
    - UV_PUBLISH_USERNAME=$TWINE_USERNAME UV_PUBLISH_PASSWORD=$TWINE_PASSWORD uv publish
  only:
    - /v.*/
